/**
 * server/src/models/walletTransaction.ts
 *
 * Records every organization wallet top-up attempt against PayMe, so a
 * webhook that arrives more than once (network retry, provider replay)
 * cannot credit the same wallet twice, and so completed/failed attempts
 * have an audit trail.
 */

import mongoose from "mongoose";

export interface WalletTransactionDoc extends mongoose.Document {
  organizationId: mongoose.Types.ObjectId;
  requestId: string;
  amount: number;
  currency: string;
  status: "pending" | "completed" | "failed";
  payMeTransactionId?: string;
  rawWebhookPayload?: unknown;
  requestedAt: Date;
  completedAt?: Date;
}

const WalletTransactionSchema = new mongoose.Schema(
  {
    organizationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Organization",
      required: true,
      index: true,
    },
    // Generated by us at initiate-time, before PayMe has assigned its own
    // transaction id - this is what correlates the webhook back to the
    // wallet top-up request that triggered it.
    requestId: {
      type: String,
      required: true,
      unique: true,
    },
    amount: {
      type: Number,
      required: true,
    },
    currency: {
      type: String,
      default: "ILS",
    },
    status: {
      type: String,
      enum: ["pending", "completed", "failed"],
      default: "pending",
      index: true,
    },
    // Only known once PayMe's webhook fires; sparse so multiple pending
    // rows (still null) don't collide on the unique index.
    payMeTransactionId: {
      type: String,
      unique: true,
      sparse: true,
    },
    rawWebhookPayload: mongoose.Schema.Types.Mixed,
    requestedAt: {
      type: Date,
      default: Date.now,
    },
    completedAt: Date,
  },
  { timestamps: true },
);

WalletTransactionSchema.index({ organizationId: 1, requestedAt: -1 });

export const WalletTransaction = mongoose.model<WalletTransactionDoc>(
  "WalletTransaction",
  WalletTransactionSchema,
);
